openapi: 3.0.1
info:
  title: vtp
  description: API for brev generering for foreldrepenger og svangerskapspenger
  license:
    name: MIT
    url: http://nav.no
  version: "1.0"
servers:
  - url: /fpdokgen
paths:
  /forvaltning/api/health/isAlive:
    get:
      operationId: isAlive
      responses:
        default:
          description: default response
          content:
            '*/*': { }
  /forvaltning/api/health/isReady:
    get:
      operationId: isReady
      responses:
        default:
          description: default response
          content:
            '*/*': { }
  /forvaltning/api/health/preStop:
    get:
      operationId: preStop
      responses:
        default:
          description: default response
          content:
            '*/*': { }
  /forvaltning/api/dokument/{navn}/create-pdf:
    post:
      summary: Lager en PDF av flettefeltene og malen med angitt variation.
      description: PDF er av versjonen PDF/A
      operationId: createPdf
      parameters:
        - name: navn
          in: path
          required: true
          schema:
            type: string
        - name: språk
          in: query
          schema:
            type: string
            default: BOKMÅL
            enum:
              - BOKMÅL
              - NYNORSK
              - ENGELSK
        - name: styling
          in: query
          schema:
            type: string
            default: PDF
            enum:
              - PDF
              - HTML
              - PDFINNTEKTSMELDING
      requestBody:
        description: JSON-data som skal flettes inn i malen. Må validere mot malens
          skjema.
        content:
          application/json:
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            '*/*': { }
  /forvaltning/api/application.wadl/{path}:
    get:
      operationId: getExternalGrammar
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: default response
          content:
            application/xml: { }
  /forvaltning/api/application.wadl:
    get:
      operationId: getWadl
      responses:
        default:
          description: default response
          content:
            application/vnd.sun.wadl+xml: { }
            application/xml: { }
